In [31]:
import pandas as pd
import numpy as np
import glob

In [32]:
files = glob.glob('../data/raw/*.csv')

df_list = []

for file in files:
    temp_df = pd.read_csv(file)
    df_list.append(temp_df)

df = pd.concat(df_list, ignore_index= True)

print("Dataset shape", df.shape)

Dataset shape (2193, 8)

In [33]:
df.head()

,Location,time,precipitation_sum,temperature_2m_mean,relative_humidity_2m_mean,surface_pressure_mean,wind_speed_10m_max,river_discharge
0,"An Khanh, Hoai Duc, Ha Noi",2024-06-09,23.4,27.0,93,1002.4,9.5,19.61
1,"An Khanh, Hoai Duc, Ha Noi",2024-06-10,29.1,27.1,91,1003.9,12.6,21.44
2,"An Khanh, Hoai Duc, Ha Noi",2024-06-11,3.9,28.5,87,1003.4,11.9,15.71
3,"An Khanh, Hoai Duc, Ha Noi",2024-06-12,0.2,30.2,82,1002.2,14.5,11.74
4,"An Khanh, Hoai Duc, Ha Noi",2024-06-13,0.0,31.3,77,999.3,11.9,8.12

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2193 entries, 0 to 2192
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Location                   2193 non-null   object
 1   time                       2193 non-null   object
 2   precipitation_sum          2193 non-null   float64
 3   temperature_2m_mean        2193 non-null   float64
 4   relative_humidity_2m_mean  2193 non-null   int64
 5   surface_pressure_mean      2193 non-null   float64
 6   wind_speed_10m_max         2193 non-null   float64
 7   river_discharge            2193 non-null   float64
dtypes: float64(5), int64(1), object(2)
memory usage: 137.2+ KB

In [35]:
df.describe()

,precipitation_sum,temperature_2m_mean,relative_humidity_2m_mean,surface_pressure_mean,wind_speed_10m_max,river_discharge
count,2193.000000,2193.000000,2193.000000,2193.000000,2193.000000,2193.000000
mean,6.429640,24.471683,78.992248,1009.826083,14.454218,1354.088057
std,13.608226,4.705788,9.094367,7.266010,4.449947,3324.915373
min,0.000000,11.400000,43.000000,990.000000,5.400000,0.090000
25%,0.000000,20.800000,74.000000,1003.800000,11.300000,0.750000
50%,0.600000,25.800000,81.000000,1009.300000,14.400000,4.500000
75%,6.400000,28.200000,86.000000,1015.800000,17.000000,682.910000
max,134.000000,33.400000,96.000000,1029.600000,59.000000,29579.140000

In [36]:
df = df.rename(columns = {
    "Location": "location",
    "time": "date",
    "precipitation_sum": "rainfall",
    "temperature_2m_mean": "temperature",
    "relative_humidity_2m_mean": "humidity",
    "surface_pressure_mean": "pressure",
    "wind_speed_10m_max": "wind_speed"
})

In [37]:
df["date"] = pd.to_datetime(df["date"])

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2193 entries, 0 to 2192
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   location         2193 non-null   object
 1   date             2193 non-null   datetime64[ns]
 2   rainfall         2193 non-null   float64
 3   temperature      2193 non-null   float64
 4   humidity         2193 non-null   int64
 5   pressure         2193 non-null   float64
 6   wind_speed       2193 non-null   float64
 7   river_discharge  2193 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(1)
memory usage: 137.2+ KB

In [39]:
location_split = df['location'].str.split(", ",expand = True)

df["ward"] = location_split[0]
df["district"] = location_split[1]
df["city"] = location_split[2]

In [40]:
df.duplicated().sum()

np.int64(0)

In [41]:
df.head()

,location,date,rainfall,temperature,humidity,pressure,wind_speed,river_discharge,ward,district,city
0,"An Khanh, Hoai Duc, Ha Noi",2024-06-09,23.4,27.0,93,1002.4,9.5,19.61,An Khanh,Hoai Duc,Ha Noi
1,"An Khanh, Hoai Duc, Ha Noi",2024-06-10,29.1,27.1,91,1003.9,12.6,21.44,An Khanh,Hoai Duc,Ha Noi
2,"An Khanh, Hoai Duc, Ha Noi",2024-06-11,3.9,28.5,87,1003.4,11.9,15.71,An Khanh,Hoai Duc,Ha Noi
3,"An Khanh, Hoai Duc, Ha Noi",2024-06-12,0.2,30.2,82,1002.2,14.5,11.74,An Khanh,Hoai Duc,Ha Noi
4,"An Khanh, Hoai Duc, Ha Noi",2024-06-13,0.0,31.3,77,999.3,11.9,8.12,An Khanh,Hoai Duc,Ha Noi

In [42]:
df.drop(columns = ['location'],inplace = True)

In [43]:
df.head()

,date,rainfall,temperature,humidity,pressure,wind_speed,river_discharge,ward,district,city
0,2024-06-09,23.4,27.0,93,1002.4,9.5,19.61,An Khanh,Hoai Duc,Ha Noi
1,2024-06-10,29.1,27.1,91,1003.9,12.6,21.44,An Khanh,Hoai Duc,Ha Noi
2,2024-06-11,3.9,28.5,87,1003.4,11.9,15.71,An Khanh,Hoai Duc,Ha Noi
3,2024-06-12,0.2,30.2,82,1002.2,14.5,11.74,An Khanh,Hoai Duc,Ha Noi
4,2024-06-13,0.0,31.3,77,999.3,11.9,8.12,An Khanh,Hoai Duc,Ha Noi

In [44]:
import os

output_path = '../data/cleaned/cleaned_weather.csv'

# Xóa file cũ nếu đã tồn tại
if os.path.exists(output_path):
    os.remove(output_path)
    print(f"Deleted existing file: {output_path}")

# Export CSV
df.to_csv(output_path, index=True)

print('Done')

Deleted existing file: ../data/cleaned/cleaned_weather.csv
Done